// src/pages/Home.svelte
<script>
  import Comment from '../components/Comment.svelte';

  let count = $state(0);
</script>

<section class="bg-gray-100 p-8 text-gray-700">
  <h1 class="text-2xl font-bold">Home</h1>
  <p class="mt-4">这不是首页，这是一个计数器</p>

  <div class="mt-4 flex items-center space-x-2">
    <button
      class="rounded-lg border border-gray-900 px-2"
      onclick={() => count--}
    >
      -
    </button>

    <output class="p-2">Count: {count}</output>

    <button
      class="rounded-lg border border-gray-900 px-2"
      onclick={() => count++}
    >
      +
    </button>
  </div>
</section>

<div class="mx-auto my-4 mt-8 max-w-screen-md px-4">
  <Comment />
</div>

// src/pages/Home.tsx
import { createSignal } from 'solid-js'
import Comment from '../components/Comment'

export default function Home() {
  const [count, setCount] = createSignal(0)

  return (
    <>
      <section class="bg-gray-100 p-8 text-gray-700">
        <h1 class="text-2xl font-bold">Home</h1>
        <p class="mt-4">这不是首页，这是一个计数器</p>

        <div class="mt-4 flex items-center space-x-2">
          <button
            class="rounded-lg border border-gray-900 px-2"
            onClick={() => setCount(count() - 1)}
          >
            -
          </button>

          <output class="p-2">Count: {count()}</output>

          <button
            class="rounded-lg border border-gray-900 px-2"
            onClick={() => setCount(count() + 1)}
          >
            +
          </button>
        </div>
      </section>

      <div class="mx-auto my-4 mt-8 max-w-screen-md px-4">
        <Comment />
      </div>
    </>
  )
}
