// src/components/Comment.svelte
<script lang="ts">
  import Giscus from '@giscus/svelte'
</script>

<Giscus
  repo="plos-clan/PlosClan-Source"
  repoId="R_kgDOKgRxiA"
  category="General"
  categoryId="DIC_kwDOKgRxiM4ChzPi"
  mapping="og:title"
  strict="0"
  reactionsEnabled="1"
  emitMetadata="0"
  inputPosition="top"
  theme="light"
  lang="zh-CN"
  loading="lazy"
/>

// src/components/Comment.tsx
import Giscus from '@giscus/solid'

export default () => {
  return (
    <Giscus
      repo="plos-clan/PlosClan-Source"
      repoId="R_kgDOKgRxiA"
      category="General"
      categoryId="DIC_kwDOKgRxiM4ChzPi"
      mapping="og:title"
      strict="0"
      reactionsEnabled="1"
      emitMetadata="0"
      inputPosition="top"
      theme="light"
      lang="zh-CN"
      loading="lazy"
    />
  )
}
