// src/App.tsx
import { useRoutes } from '@solidjs/router'
import { routes } from './routes'
import Header from './components/Header'
import TitleMeta from './components/TitleMeta'

const App = () => {
  const Route = useRoutes(routes)

  return (
    <>
      <Header />
      <TitleMeta />
      <Route />
    </>
  )
}

export default App

// src/App.svelte
<script>
  import Meta from './components/Meta.svelte';
  import Header from './components/Header.svelte';
  import { routes, routerConfig } from './routes';
  import { Router } from "@mateothegreat/svelte5-router";
  import { ModeWatcher } from "mode-watcher";
</script>

<Meta />
<ModeWatcher />

<Header />
<Router {routes} {...routerConfig} />
